extensions:
  health_check:

receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: $JOB_NAME
        scrape_interval: 150s
        honor_labels: true
        scheme: http
        authorization:
          type: Bearer
          credentials: $BEARER
        static_configs:
        - targets:
          - $TARGET
processors:
  batch/metrics:
    timeout: 60s
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers:
      - prometheus
      exporters:
      - awsprometheusremotewrite
      - logging
  extensions: [health_check]

exporters:
  logging:
    loglevel: debug
  awsprometheusremotewrite:
    endpoint: "$AMP_ENDPOINT"
    aws_auth:
      service: "aps"
      region: $AMP_REGION