extensions:
  health_check:
  sigv4auth:
    region: "$AMP_REGION"

receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: $JOB_NAME
        scrape_interval: 150s
        scrape_timeout: 30s
        honor_labels: true
        scheme: https
        oauth2:
          client_id: $CLIENT_ID
          client_secret: $CLIENT_SECRET
          token_url: $TOKEN_URL
        static_configs:
        - targets:
          - $TARGET
processors:
  batch/metrics:
    timeout: 60s
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers:
      - prometheus
      exporters:
      - prometheusremotewrite
      - logging
  extensions: [sigv4auth, health_check]

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: "$AMP_ENDPOINT"
    auth:
      authenticator: sigv4auth